import logging
from typing import Dict, Any, Optional
from apscheduler.schedulers.asyncio import AsyncIOScheduler
from app.agents.briefing_agent import generate_morning_brief

logger = logging.getLogger("nexus.scheduler")

scheduler = AsyncIOScheduler()
_latest_cached_brief: Optional[Dict[str, Any]] = None


def scheduled_morning_brief_job():
    """Triggered by APScheduler daily at 08:00 IST."""
    global _latest_cached_brief
    logger.info("Executing scheduled Morning Intelligence Brief job...")
    try:
        brief = generate_morning_brief(language_code="en-IN")
        _latest_cached_brief = brief
        logger.info("Scheduled Morning Brief successfully generated and cached.")
    except Exception as e:
        logger.error(f"Error in scheduled Morning Brief job: {e}")


def start_scheduler():
    """Start APScheduler background jobs."""
    try:
        # Schedule daily brief at 08:00
        scheduler.add_job(
            scheduled_morning_brief_job,
            "cron",
            hour=8,
            minute=0,
            id="daily_morning_brief",
            replace_existing=True
        )
        scheduler.start()
        logger.info("NEXUS APScheduler background cron started (Daily Brief at 08:00 IST).")
        # Run once on startup to warm cache
        scheduled_morning_brief_job()
    except Exception as e:
        logger.error(f"Failed to start APScheduler: {e}")


def shutdown_scheduler():
    """Stop background scheduler on shutdown."""
    if scheduler.running:
        scheduler.shutdown(wait=False)
        logger.info("NEXUS APScheduler background cron stopped.")


def get_latest_cached_brief() -> Dict[str, Any]:
    """Return the cached brief generated by the scheduler or generate fresh."""
    global _latest_cached_brief
    if not _latest_cached_brief:
        _latest_cached_brief = generate_morning_brief(language_code="en-IN")
    return _latest_cached_brief
